version: '3.3'
services:
    database:
        image: mysql
        restart: always
        command: ["--default-authentication-plugin=mysql_native_password"]
        env_file:
            - back.dev.env
        networks:
            - database_net
        volumes:
            - db_volume:/var/lib/mysql
    php:
        build:
            context: ./php
            dockerfile: Dockerfile
            args:
                - JWT_PASSPHRASE=$JWT_PASSPHRASE
                - JWT_SECRET_KEY=$JWT_SECRET_KEY
                - JWT_PUBLIC_KEY=$JWT_PUBLIC_KEY
        restart: always
        env_file:
            - back.dev.env
        depends_on:
            - database
        networks:
            - database_net
            - php_net
        volumes:
            - ./api:/var/www/api:cached
            - db_volume:/var/lib/mysql
    front:
        build:
            context: ./front
            dockerfile: Dockerfile
        restart: always
        ports:
            - "3000:3000"
        networks:
            - front_net
        volumes:
            - ./front/public:/app/public:cached
            - ./front/src:/app/src:cached
    server:
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        restart: always
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php
            - front
        networks:
            - php_net
            - front_net
        volumes:
            - ./api:/var/www/api:cached
            - /etc/letsencrypt:/etc/letsencrypt:cached

networks:
    database_net:
    php_net:
    front_net:

volumes:
    db_volume: